config/routes.rb
Rails.application.routes.draw do
  root :to => 'site#land'

  get '/lab/:id' => 'lab#land', :as => :lab_land
  get '/study/:study_id/finish' => 'study#finish', :as => :study_finish
  post '/study/:study_id/finish' => 'study#finish'

  get '/study/:study_id/instrument/:instrument_id' => 'study#instrument', :as => :study_instrument
  post '/study/:study_id/instrument/:instrument_id' => 'study#instrument'

  get '/study/:study_id' => 'study#start', :as => :study_start
  post '/study/:study_id' => 'study#start'


  devise_for :experimenters

  namespace :experimenter do
    root :to => 'site#dashboard'
    put '/participants/:id' => 'participants#update'
    get 'shared_data', to: 'site#shared_data', as: :shared_data
    resources :experimenters
    resources :labs
    resources :studies do
      get 'data', :on => :member
      resources :participants do
        resources :virtual_navigation_logs, :only => :show
      end
    end
  end
end

app/models/experimenter.rb
class Experimenter < ApplicationRecord

  belongs_to :lab
  has_many :studies

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_presence_of :first_name, :last_name, :email, :lab
  validates_uniqueness_of :email
  validate :strong_password

  def full_name
    "#{first_name} #{last_name}"
  end


  def name
  	full_name
  end
  
  def strong_password
    return if password.blank? || password =~ /(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-])/

    errors.add :password, 'Complexity requirement not met. Please use: 1 uppercase, 1 lowercase, 1 digit and 1 special character'
  end
end

app/models/study.rb
class Study < ApplicationRecord
  belongs_to :lab
  belongs_to :experimenter
  has_many :instrument_in_studies, -> { order(order: :asc) }, dependent: :destroy
  has_many :participants, -> { order(created_at: :desc) }, dependent: :destroy
  before_save :set_buttons_to_vambler
  validates_presence_of :name, :lab, :experimenter

  accepts_nested_attributes_for :instrument_in_studies, :allow_destroy => true

  after_initialize :default_values
  def default_values
    self.ask_participant_id ||= false
  end

  def last_administered
    if p = participants.first
      p.created_at
    else
      return nil
    end
  end
  def set_buttons_to_vambler
    kind_of_start_buttons = 'vambler'
  end
end

app/controllers/experimenter/experimenters_controller.rb
class Experimenter::ExperimentersController < ApplicationController
  before_action :authenticate_experimenter!
  
  def index
    if current_experimenter.administrator
      @experimenters = Experimenter.all
    else
      @experimenters = current_experimenter.lab.experimenters
    end
      @experimenters = @experimenters.includes(:lab, :studies)
  end
  
  def new
    @experimenter = Experimenter.new
  end
  
  def show
    @experimenter = Experimenter.find(params[:id])
  end
  
  def edit
    @experimenter = Experimenter.find(params[:id])
  end
  
  def create
    @experimenter = Experimenter.new(experimenter_params)

    respond_to do |format|
      if @experimenter.save
        flash[:success] = "Experimenter record created for <strong>#{@experimenter.full_name}</strong>."
        format.html { redirect_to(experimenter_experimenter_url(@experimenter)) }
      else
        format.html { render :action => "new" }
      end
    end
  end
  
  def update
    @experimenter = Experimenter.find(params[:id])

    respond_to do |format|
      if @experimenter.update_attributes(experimenter_params)
        flash[:success] = "Experimenter record updated for <strong>#{@experimenter.full_name}</strong>."
        format.html { redirect_to(experimenter_experimenter_url(@experimenter)) }
      else
        format.html { render :action => "edit" }
      end
    end
  end
  
  def destroy
    @experimenter = Experimenter.find(params[:id])
    @experimenter.destroy

    respond_to do |format|
      flash[:success] = "Experimenter record deleted for <strong>#{@experimenter.full_name}</strong>."
      format.html { redirect_to(experimenter_experimenters_url) }
    end
  end
  private

  def experimenter_params
    params.require(:experimenter).permit(:id, :lab_id, :first_name, :last_name, :lab_manager, :administrator, :email, :password, :password_confirmation)
  end
end

app/controllers/experimenter/labs_controller.rb
class Experimenter::LabsController < ApplicationController
  before_action :authenticate_experimenter!

  def index
    @labs = Lab.all.includes(:experimenters, :studies)
  end

  def new
    @lab = Lab.new
  end

  def show
    @lab = Lab.find(params[:id])
  end

  def edit
    @lab = Lab.find(params[:id])
  end

  def create
    @lab = Lab.new(lab_params)

    respond_to do |format|
      if @lab.save
        flash[:success] = "Lab record created for <strong>#{@lab.name}</strong>."
        format.html { redirect_to(experimenter_lab_url(@lab)) }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    @lab = Lab.find(params[:id])

    respond_to do |format|
      if @lab.update_attributes(lab_params)
        flash[:success] = "Lab record updated for <strong>#{@lab.name}</strong>."
        format.html { redirect_to(experimenter_lab_url(@lab)) }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @lab = Lab.find(params[:id])
    @lab.destroy

    respond_to do |format|
      flash[:success] = "Lab record deleted for <strong>#{@lab.name}</strong>."
      format.html { redirect_to(experimenter_labs_url) }
    end
  end
  def lab_params
    params.require(:lab).permit(:name, :web_site, :country, :id)
  end
end

app/controllers/experimenter/participants_controller.rb
class Experimenter::ParticipantsController < ApplicationController
  before_action :authenticate_experimenter!

  def index
    @study = Study.find(params[:study_id])
    @participants = @study.participants
  end

  def show
    @participant = Participant.find(params[:id])
  end

  def update
    @participant = Participant.find(params[:id])
    @participant.update_attributes(participant_params)
    render json: { success: true }
  end

  def destroy
    @participant = Participant.find(params[:id])
    @participant.destroy

    respond_to do |format|
      flash[:success] = "Participant records deleted for <strong>#{@participant.identification}</strong>."
      format.html { redirect_to(experimenter_study_url(@participant.study)) }
    end
  end

  def participant_params
    params.require(:participant).permit(:id, :pilot_subject, :identification)
  end
end

app/controllers/experimenter/site_controller.rb
class Experimenter::SiteController < ApplicationController
  before_action :authenticate_experimenter!

  def dashboard
    if current_experimenter.administrator
      @labs = Lab.where('')
      @studies = Study.where('')
      @experimenters = Experimenter.where('')
    else
      @studies = current_experimenter.lab.studies
      @experimenters = current_experimenter.lab.experimenters
    end
  end

  def shared_data
    @participants_with_currently_shared_data = Participant.with_currently_shared_data
    if params[:table]
      @table = params[:table]
    else
      @table = 'spatial-ability-and-demographics'
    end
  end
end

app/controllers/experimenter/studies_controller.rb
class Experimenter::StudiesController < ApplicationController
  before_action :authenticate_experimenter!

  def index
    if current_experimenter.administrator
      @studies = Study.all
    else
      @studies = current_experimenter.lab.studies
    end
      @studies = @studies.includes(:experimenter, :participants)
  end

  def new
    @study = Study.new
  end

  def show
    @study = Study.find(params[:id])
  end

  def data
    @study = Study.find(params[:id])

    if params[:table]
      @table = params[:table]
    else
      @table = 'spatial-ability-and-demographics'
    end
  end

  def edit
    @study = Study.find(params[:id])
  end

  def create
    @study = Study.new(study_params)
    respond_to do |format|
      if @study.save
        flash[:success] = "Study record created for <strong>#{@study.name}</strong>."
        format.html { redirect_to(experimenter_study_url(@study)) }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    @study = Study.find(params[:id])

    respond_to do |format|
      if @study.update_attributes(study_params)
        flash[:success] = "Study record updated for <strong>#{@study.name}</strong>."
        format.html { redirect_to(experimenter_study_url(@study)) }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @study = Study.find(params[:id])
    @study.destroy

    respond_to do |format|
      flash[:success] = "Study record deleted for <strong>#{@study.name}</strong>."
      format.html { redirect_to(experimenter_studies_url) }
    end
  end
  private
  def study_params
    params.require(:study).permit(:name, :lab_id, :experimenter_id, :active, :ask_participant_id, :when_to_share_data, :kind_of_start_buttons, :welcome_text, :completion_text, instrument_in_studies_attributes: [:order, :instrument, :version, :randomize, :force_wait, :id, :_destroy])
  end
end

app/controllers/experimenter/virtual_navigation_logs_controller.rb
class Experimenter::VirtualNavigationLogsController < ApplicationController
  before_action :authenticate_experimenter!

  def show
    @virtual_navigation_log = VirtualNavigationLog.find(params[:id])
    render :plain => @virtual_navigation_log.log
  end
end

app/views/experimenter/studies/_table.html.erb
<% if current_experimenter.administrator %>
<h2>All Studies</h2>
<% else %>
<h2><%= current_experimenter.lab.name %> Studies</h2>
<% end %>

<table class="table table-striped">
  <thead>
    <th>Study Name</th>
    <th>Active?</th>
    <th>Last administered</th>
    <th>&#35; of participants</th>
    <th>When to share data</th>
    <th>&#35; of participants currently shared</th>
    <th>Primary experimenter</th>
  </thead>
  <% for study in @studies.includes(:experimenter, :participants => :study) %>
  <tr>
    <td><strong><%= link_to study.name, experimenter_study_path(study) %></strong></td>
    <td><% if study.active %><img src="/images/icon-lightbulb.png" alt="Active"/><% end %></td>
    <td>
      <% if study.last_administered %>
        <%= time_ago_in_words study.last_administered %> ago
      <% else %>
        never
      <% end %>
    </td>
    <td><%= pluralize(study.participants.length, "participant")%></td>
    <td><%= study.when_to_share_data %></td>
    <td>
      <%- if study.participants.select{|p| p.share_data == true && ( p.study.when_to_share_data == 'immediately' or (p.study.when_to_share_data == '3years' and p.created_at <= 3.years.ago))}.count > 0 %>
        <%= pluralize(study.participants.select{|p| p.share_data == true && ( p.study.when_to_share_data == 'immediately' or (p.study.when_to_share_data == '3years' and p.created_at <= 3.years.ago   )  ) }.count, "participant")%>
      <%- end %>
    </td>
    <td><%= link_to study.experimenter.full_name, experimenter_experimenter_path(study.experimenter) %>
  </tr>
  <% end %>
</table>

app/views/experimenter/studies/edit.slim
- content_for :body do
  = simple_form_for([:experimenter, @study], :html => { :class => 'form-horizontal' }) do |f|
    h1 = @study.name
    ul.nav.nav-tabs
      li
        = link_to "View Study", experimenter_study_path(@study)
      li.active 
        a Edit Study
        
    - if f.error_messages
      = f.error_messages :class => "alert alert-error", :header_tag => :strong
    = f.input :name
    = f.association :experimenter, :as => :select, :label => 'Primary experimenter', :collection => @study.lab.experimenters, :include_blank => false
    = f.input :active
    
    h3 Participant Id
    = f.select :ask_participant_id, [['Auto Assign', false], ['Experimenter Assign', true]]

    h3 When to Share Data
    = f.select :when_to_share_data, [['Immediately', 'immediately'], ['After 3 Years', '3years']]

    h2 Instruments
    p#add-another-instrument
      ' Add another instrument: 
      select#instrument-to-add-select
        option Virtual SILCton Demographics Questionnaire
        option SBSOD (fixed order)
        option PSAS (short version, randomized)
        option PSAS (long version, randomized)
        option PVAS (randomized)
        option MRT (forced wait)
        option Virtual SILCton Route Learning (Main Routes)
        option Virtual SILCton Route Learning (Connector Routes)
        option Virtual SILCton Route Learning (Main Routes A)
        option Virtual SILCton Route Learning (Main Routes B)
        option Virtual SILCton Route Learning (Connector Routes C1)
        option Virtual SILCton Route Learning (Connector Routes C2)
        option Virtual SILCton Free Exploration
        option Virtual SILCton On-site Pointing
        option Virtual SILCton Off-site Pointing
        option Virtual SILCton Distance Estimates
        option Virtual SILCton Map Arrangements
      ' 
      a.btn.btn-primary#add-button Add
    p Drag rows up and down to reorder the instruments.
    table.table#instruments-in-study-table
      thead
        tr
          th Order
          th Instrument
          th Version
          th Randomize?
        tbody
          = f.fields_for :instrument_in_studies do |iis|
            tr
              td
                span.order = iis.object.order + 1
                = iis.input :order, :as => :hidden, :input_html => {:class => 'order-field'}
              td
                = iis.object.instrument
                = iis.input :instrument, :as => :hidden
              td 
                = iis.object.version
                = iis.input :version, :as => :hidden
              td 
                = iis.object.randomize ? 'yes' : ''
                = iis.input :randomize, :as => :hidden
              td
                a.btn.btn-danger.remove-button Remove
                = iis.hidden_field :_destroy, :class => 'destroy-field'

    h2 Instructions
    = f.input :welcome_text, :input_html => {:class => 'span6'}
    = f.input :completion_text, :input_html => {:class => 'span6'}

    .form-actions
      = link_to "Cancel", experimenter_study_path(@study), {:class => "btn", :style => 'margin-right: 10px;'}
      = f.submit "Save Study", {:class => "btn btn-primary"}

  h2 Delete Study
  p Deleting this study will permanently remove all associated participant records.
  .form-horizontal
    .form-actions
      = button_to "Delete Study", experimenter_study_path(@study), :method => :delete, :class => "btn btn-danger", :confirm => "Are you sure you want to delete #{@study.name}?"
      
= render :template => '/experimenter/layout'

app/views/experimenter/studies/index.slim
- content_for :body do
  = render "table"
  - if current_experimenter.administrator or current_experimenter.lab_manager
    .pull-right
      = link_to "Create Study", new_experimenter_study_path, :class => "btn btn-primary"
= render :template => '/experimenter/layout'

app/views/experimenter/studies/new.slim

- content_for :body do
  = simple_form_for([:experimenter, @study], :html => { :class => 'form-horizontal' }) do |f|
    h1 New Study

    - if f.error_messages
      = f.error_messages :class => "alert alert-error", :header_tag => :strong
    = f.input :name
    - if current_experimenter.administrator
      = f.association :lab, :as => :select, :include_blank => false
      = f.association :experimenter, :as => :select, :label => 'Primary experimenter', :collection => Experimenter.all, :include_blank => false
    - else
      = f.association :lab, :as => :select, :include_blank => false, :collection => [current_experimenter.lab]
      = f.association :experimenter, :as => :select, :label => 'Primary experimenter', :collection => current_experimenter.lab.experimenters, :include_blank => false
    = f.input :active, :label => 'Active?'

    h3 Participant Id
    = f.select :ask_participant_id, [['Auto Assign', false], ['Experimenter Assign', true]]

    h3 When to Share Data
    = f.select :when_to_share_data, [['Immediately', 'immediately'], ['After 3 Years', '3years']]

    h2 Instruments
    p#add-another-instrument
      ' Add another instrument: 
      select#instrument-to-add-select
        option Virtual SILCton Demographics Questionnaire
        option SBSOD (fixed order)
        option PSAS (short version, randomized)
        option PSAS (long version, randomized)
        option PVAS (randomized)
        option MRT (forced wait)
        option Virtual SILCton Route Learning (Main Routes)
        option Virtual SILCton Route Learning (Connector Routes)
        option Virtual SILCton Route Learning (Main Routes A)
        option Virtual SILCton Route Learning (Main Routes B)
        option Virtual SILCton Route Learning (Connector Routes C1)
        option Virtual SILCton Route Learning (Connector Routes C2)
        option Virtual SILCton Free Exploration
        option Virtual SILCton On-site Pointing
        option Virtual SILCton Off-site Pointing
        option Virtual SILCton Distance Estimates
        option Virtual SILCton Map Arrangements
      ' 
      a.btn.btn-primary#add-button Add
    p Drag rows up and down to reorder the instruments.
    table.table#instruments-in-study-table
      thead
        tr
          th Order
          th Instrument
          th Version
          th Randomize?
        tbody
          = f.fields_for :instrument_in_studies do |iis|
            tr
              td
                span.order = iis.object.order + 1
                = iis.input :order, :as => :hidden, :input_html => {:class => 'order-field'}
              td 
                = iis.object.instrument
                = iis.input :instrument, :as => :hidden
              td 
                = iis.object.version
                = iis.input :version, :as => :hidden
              td 
                = iis.object.randomize ? 'yes' : ''
                = iis.input :randomize, :as => :hidden
              td
                a.btn.btn-danger.remove-button Remove
                = iis.hidden_field :_destroy, :class => 'destroy-field'

    h2 Instructions
    = f.input :welcome_text, :input_html => {:class => 'span6'}
    = f.input :completion_text, :input_html => {:class => 'span6'}
          
    .form-actions
      = link_to "Cancel", experimenter_studies_path, {:class => "btn", :style => 'margin-right: 10px;'}
      = f.submit "Save Study", {:class => "btn btn-primary"}
      
= render :template => '/experimenter/layout'

app/views/experimenter/studies/show.slim
- content_for :body do
  h1 = @study.name
  ul.nav.nav-tabs
    li.active
      a href="#view" data-toggle="tab" View Study
    - if current_experimenter == @study.experimenter or current_experimenter.lab_manager or current_experimenter.administrator
      li
        = link_to "Edit Study", edit_experimenter_study_path(@study)
    li
      a href="#participants" data-toggle="tab" View Participants
    li
      = link_to "View Data", data_experimenter_study_path(@study)

  .tab-content
    .tab-pane.active#settings
      p
        strong Active?
        - if @study.active
          span style="color: green;" Yes, currently active.
        - else
          span style="color: red;" Not currently active.

      p 
        strong URL for participants: 
        = link_to study_start_url(@study), study_start_url(@study)

      p
        strong Participant identification:
        ul
          li Id
          - if @study.ask_participant_id
            span Experimenter Assign
          - else 
            span Auto Assign
          - if @study.ask_name
            li Ask for name (first and last)
          - if @study.ask_email
            li Ask for e-mail address
          - if @study.ask_age
            li Ask for age
          - if @study.ask_sex
            li Ask for sex

      p
        strong When to share data: 
        = @study.when_to_share_data



      h2 Instruments
      table.table.table-striped
        thead
          tr
            th Order
            th Instrument Name
            th Version
        tbody
          - for instrument in @study.instrument_in_studies
            tr
              td = instrument.order + 1
              td
                - if instrument.instrument == 'Static Page'
                  = instrument.static_page.name
                - else 
                  = instrument.instrument
              td = instrument.version

      h2 Instructions
      p
        strong Welcome text: 
        == @study.welcome_text
      p
        strong Completion text: 
        == @study.completion_text

    .tab-pane#participants
      table.table.table-striped.data-table#study-participants-table
        thead
          tr
            th Participant Identification
            th Participant UUID
            th Pilot subject?
            th Elected to share data?
            th Age
            th Sex
            th Date
            - if current_experimenter == @study.experimenter or current_experimenter.lab_manager or current_experimenter.administrator
              th Actions
        tbody
          - for p in @study.participants.includes(:study)
            tr data-id=p.id
              td = text_field_tag 'participant-id', p.identification, disabled: !@study.ask_participant_id
              td = p.uuid
              td = check_box_tag 'pilot-subject', 1, p.pilot_subject
              td = p.share_data ? 'yes' : 'no'
              td = p.age
              td = p.sex
              td = p.created_at
              - if current_experimenter == @study.experimenter or current_experimenter.lab_manager or current_experimenter.administrator
                td= button_to "Delete", experimenter_study_participant_path(p.study, p), :method => :delete, :class => "btn btn-danger", :confirm => "Are you sure you want to delete the records for #{p.identification}?"

= render :template => '/experimenter/layout'