config/routes.rb
Rails.application.routes.draw do
  root :to => 'site#land'

  get '/lab/:id' => 'lab#land', :as => :lab_land
  get '/study/:study_id/finish' => 'study#finish', :as => :study_finish
  post '/study/:study_id/finish' => 'study#finish'

  get '/study/:study_id/instrument/:instrument_id' => 'study#instrument', :as => :study_instrument
  post '/study/:study_id/instrument/:instrument_id' => 'study#instrument'

  get '/study/:study_id' => 'study#start', :as => :study_start
  post '/study/:study_id' => 'study#start'


  devise_for :experimenters

  namespace :experimenter do
    root :to => 'site#dashboard'
    put '/participants/:id' => 'participants#update'
    get 'shared_data', to: 'site#shared_data', as: :shared_data
    resources :experimenters
    resources :labs
    resources :studies do
      get 'data', :on => :member
      resources :participants do
        resources :virtual_navigation_logs, :only => :show
      end
    end
  end
end

app/models/experimenter.rb
class Experimenter < ApplicationRecord

  belongs_to :lab
  has_many :studies

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_presence_of :first_name, :last_name, :email, :lab
  validates_uniqueness_of :email
  validate :strong_password

  def full_name
    "#{first_name} #{last_name}"
  end


  def name
  	full_name
  end
  
  def strong_password
    return if password.blank? || password =~ /(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-])/

    errors.add :password, 'Complexity requirement not met. Please use: 1 uppercase, 1 lowercase, 1 digit and 1 special character'
  end
end

app/models/lab.rb
class Lab < ApplicationRecord
  has_many :experimenters, :dependent => :destroy
  has_many :studies, :dependent => :destroy

  validates_presence_of :name
  validates_uniqueness_of :name
end

app/controllers/experimenter/experimenters_controller.rb
class Experimenter::ExperimentersController < ApplicationController
  before_action :authenticate_experimenter!
  
  def index
    if current_experimenter.administrator
      @experimenters = Experimenter.all
    else
      @experimenters = current_experimenter.lab.experimenters
    end
      @experimenters = @experimenters.includes(:lab, :studies)
  end
  
  def new
    @experimenter = Experimenter.new
  end
  
  def show
    @experimenter = Experimenter.find(params[:id])
  end
  
  def edit
    @experimenter = Experimenter.find(params[:id])
  end
  
  def create
    @experimenter = Experimenter.new(experimenter_params)

    respond_to do |format|
      if @experimenter.save
        flash[:success] = "Experimenter record created for <strong>#{@experimenter.full_name}</strong>."
        format.html { redirect_to(experimenter_experimenter_url(@experimenter)) }
      else
        format.html { render :action => "new" }
      end
    end
  end
  
  def update
    @experimenter = Experimenter.find(params[:id])

    respond_to do |format|
      if @experimenter.update_attributes(experimenter_params)
        flash[:success] = "Experimenter record updated for <strong>#{@experimenter.full_name}</strong>."
        format.html { redirect_to(experimenter_experimenter_url(@experimenter)) }
      else
        format.html { render :action => "edit" }
      end
    end
  end
  
  def destroy
    @experimenter = Experimenter.find(params[:id])
    @experimenter.destroy

    respond_to do |format|
      flash[:success] = "Experimenter record deleted for <strong>#{@experimenter.full_name}</strong>."
      format.html { redirect_to(experimenter_experimenters_url) }
    end
  end
  private

  def experimenter_params
    params.require(:experimenter).permit(:id, :lab_id, :first_name, :last_name, :lab_manager, :administrator, :email, :password, :password_confirmation)
  end
end

app/controllers/experimenter/labs_controller.rb
class Experimenter::LabsController < ApplicationController
  before_action :authenticate_experimenter!

  def index
    @labs = Lab.all.includes(:experimenters, :studies)
  end

  def new
    @lab = Lab.new
  end

  def show
    @lab = Lab.find(params[:id])
  end

  def edit
    @lab = Lab.find(params[:id])
  end

  def create
    @lab = Lab.new(lab_params)

    respond_to do |format|
      if @lab.save
        flash[:success] = "Lab record created for <strong>#{@lab.name}</strong>."
        format.html { redirect_to(experimenter_lab_url(@lab)) }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    @lab = Lab.find(params[:id])

    respond_to do |format|
      if @lab.update_attributes(lab_params)
        flash[:success] = "Lab record updated for <strong>#{@lab.name}</strong>."
        format.html { redirect_to(experimenter_lab_url(@lab)) }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @lab = Lab.find(params[:id])
    @lab.destroy

    respond_to do |format|
      flash[:success] = "Lab record deleted for <strong>#{@lab.name}</strong>."
      format.html { redirect_to(experimenter_labs_url) }
    end
  end
  def lab_params
    params.require(:lab).permit(:name, :web_site, :country, :id)
  end
end

app/controllers/experimenter/participants_controller.rb
class Experimenter::ParticipantsController < ApplicationController
  before_action :authenticate_experimenter!

  def index
    @study = Study.find(params[:study_id])
    @participants = @study.participants
  end

  def show
    @participant = Participant.find(params[:id])
  end

  def update
    @participant = Participant.find(params[:id])
    @participant.update_attributes(participant_params)
    render json: { success: true }
  end

  def destroy
    @participant = Participant.find(params[:id])
    @participant.destroy

    respond_to do |format|
      flash[:success] = "Participant records deleted for <strong>#{@participant.identification}</strong>."
      format.html { redirect_to(experimenter_study_url(@participant.study)) }
    end
  end

  def participant_params
    params.require(:participant).permit(:id, :pilot_subject, :identification)
  end
end

app/controllers/experimenter/site_controller.rb
class Experimenter::SiteController < ApplicationController
  before_action :authenticate_experimenter!

  def dashboard
    if current_experimenter.administrator
      @labs = Lab.where('')
      @studies = Study.where('')
      @experimenters = Experimenter.where('')
    else
      @studies = current_experimenter.lab.studies
      @experimenters = current_experimenter.lab.experimenters
    end
  end

  def shared_data
    @participants_with_currently_shared_data = Participant.with_currently_shared_data
    if params[:table]
      @table = params[:table]
    else
      @table = 'spatial-ability-and-demographics'
    end
  end
end

app/controllers/experimenter/studies_controller.rb
class Experimenter::StudiesController < ApplicationController
  before_action :authenticate_experimenter!

  def index
    if current_experimenter.administrator
      @studies = Study.all
    else
      @studies = current_experimenter.lab.studies
    end
      @studies = @studies.includes(:experimenter, :participants)
  end

  def new
    @study = Study.new
  end

  def show
    @study = Study.find(params[:id])
  end

  def data
    @study = Study.find(params[:id])

    if params[:table]
      @table = params[:table]
    else
      @table = 'spatial-ability-and-demographics'
    end
  end

  def edit
    @study = Study.find(params[:id])
  end

  def create
    @study = Study.new(study_params)
    respond_to do |format|
      if @study.save
        flash[:success] = "Study record created for <strong>#{@study.name}</strong>."
        format.html { redirect_to(experimenter_study_url(@study)) }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    @study = Study.find(params[:id])

    respond_to do |format|
      if @study.update_attributes(study_params)
        flash[:success] = "Study record updated for <strong>#{@study.name}</strong>."
        format.html { redirect_to(experimenter_study_url(@study)) }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @study = Study.find(params[:id])
    @study.destroy

    respond_to do |format|
      flash[:success] = "Study record deleted for <strong>#{@study.name}</strong>."
      format.html { redirect_to(experimenter_studies_url) }
    end
  end
  private
  def study_params
    params.require(:study).permit(:name, :lab_id, :experimenter_id, :active, :ask_participant_id, :when_to_share_data, :kind_of_start_buttons, :welcome_text, :completion_text, instrument_in_studies_attributes: [:order, :instrument, :version, :randomize, :force_wait, :id, :_destroy])
  end
end

app/controllers/experimenter/virtual_navigation_logs_controller.rb
class Experimenter::VirtualNavigationLogsController < ApplicationController
  before_action :authenticate_experimenter!

  def show
    @virtual_navigation_log = VirtualNavigationLog.find(params[:id])
    render :plain => @virtual_navigation_log.log
  end
end

app/controllers/lab_controller.rb
class LabController < ApplicationController
  def land
    @lab = Lab.find(params[:id])
  end
end

app/views/experimenter/labs/_table.html.erb
<h2>Labs</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Lab name</th>
      <th>&#35; of experimenters</th>
      <th>&#35; of studies</th>
    </tr>
  </thead>
  <% for lab in @labs.includes(:experimenters, :studies) %>
  <tr>
    <td><strong><%= link_to lab.name, experimenter_lab_path(lab) %></strong></td>
    <td><%= pluralize(lab.experimenters.length, "study") %></td>
    <td><%= pluralize(lab.studies.length, "study") %></td>
  </tr>
  <% end %>
</table>

app/views/experimenter/labs/edit.slim
- content_for :body do
  = simple_form_for([:experimenter, @lab], :html => { :class => 'form-horizontal' }) do |f|
    h1 = @lab.name
    ul.nav.nav-tabs
      li
        = link_to "View", experimenter_lab_path(@lab)
      li.active
        a Edit
        
    - if f.error_messages
      = f.error_messages :class => "alert alert-error", :header_tag => :strong
    = f.input :name
    = f.input :web_site
    = f.input :country
          
    .form-actions
      = f.submit "Save Changes", {:class => "btn btn-primary"}

  h2 Delete Lab
  p Deleting this lab will permanently remove all associated studies and experimenters.
  .form-horizontal
    .form-actions
      = button_to "Delete Lab", experimenter_lab_path(@lab), :method => :delete, :class => "btn btn-danger", :confirm => "Are you sure you want to delete #{@lab.name}?"

= render :template => '/experimenter/layout'

app/views/experimenter/labs/index.slim
- content_for :body do
  = render "table"
  
  - if current_experimenter.administrator
    .pull-right
      = link_to "Create Lab", new_experimenter_lab_path, :class => "btn btn-primary"

= render :template => '/experimenter/layout'

app/views/experimenter/labs/new.slim
- content_for :body do
  = simple_form_for([:experimenter, @lab], :html => { :class => 'form-horizontal' }) do |f|
    h1 Create Lab
        
    - if f.error_messages
      = f.error_messages :class => "alert alert-error", :header_tag => :strong
    = f.input :name
    = f.input :web_site
    = f.input :country
          
    .form-actions
      = f.submit "Create Lab", {:class => "btn btn-primary"}
      
= render :template => '/experimenter/layout'

app/views/experimenter/labs/show.slim
- content_for :body do
  h1 = @lab.name
  ul.nav.nav-tabs
    li.active 
      a View
    - if current_experimenter.administrator
      li = link_to "Edit", edit_experimenter_lab_path(@lab)
  p
  	strong Web site:
  	= link_to @lab.web_site, "http://#{@lab.web_site}"
  p
    strong Country:
    = @lab.country

= render :template => '/experimenter/layout'