config/routes.rb
Rails.application.routes.draw do
  root :to => 'site#land'

  get '/lab/:id' => 'lab#land', :as => :lab_land
  get '/study/:study_id/finish' => 'study#finish', :as => :study_finish
  post '/study/:study_id/finish' => 'study#finish'

  get '/study/:study_id/instrument/:instrument_id' => 'study#instrument', :as => :study_instrument
  post '/study/:study_id/instrument/:instrument_id' => 'study#instrument'

  get '/study/:study_id' => 'study#start', :as => :study_start
  post '/study/:study_id' => 'study#start'


  devise_for :experimenters

  namespace :experimenter do
    root :to => 'site#dashboard'
    put '/participants/:id' => 'participants#update'
    get 'shared_data', to: 'site#shared_data', as: :shared_data
    resources :experimenters
    resources :labs
    resources :studies do
      get 'data', :on => :member
      resources :participants do
        resources :virtual_navigation_logs, :only => :show
      end
    end
  end
end

app/controllers/experimenter/site_controller.rb
class Experimenter::SiteController < ApplicationController
  before_action :authenticate_experimenter!

  def dashboard
    if current_experimenter.administrator
      @labs = Lab.where('')
      @studies = Study.where('')
      @experimenters = Experimenter.where('')
    else
      @studies = current_experimenter.lab.studies
      @experimenters = current_experimenter.lab.experimenters
    end
  end

  def shared_data
    @participants_with_currently_shared_data = Participant.with_currently_shared_data
    if params[:table]
      @table = params[:table]
    else
      @table = 'spatial-ability-and-demographics'
    end
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def land
  	@labs = Lab.all
  end
end

app/views/site/land.slim
doctype html
html
  head
    title Virtual SILCton
    = stylesheet_link_tag "application"
    = csrf_meta_tags
  body
    .container
      .row.well align="center"
        h1 Virtual SILCton
      .row
        .span6 align="center"
          h2 Participants
          p Please select the lab you are participating through:
          ul.unstyled
            - for lab in @labs
              li 
                h4 = link_to lab.name, lab_land_path(lab)
        .span6 align="center"
          h2 Experimenters
          a.btn.btn-inverse.btn-large href="/experimenter" Manage Your Studies
      = render 'credits_footer'